# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'GitStarred' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitStarred
  pod 'SnapKit', '~> 4.0'
  pod 'Moya', '~> 10.0'
  pod 'MoyaSugar', '~> 1.0'
  pod 'Moya-ObjectMapper'
  pod 'Alamofire', '~> 4.5'
end
